import os

env = Environment(ENV=os.environ)

cpppath = ["#../LinkItONE.Crest"]
cppflags = ['-Wall', '-Wextra', '-g']


for target in COMMAND_LINE_TARGETS:
    conscript = target+"/SConscript"
    test_objects = SConscript(conscript, exports='cpppath cppflags')

    program = env.Program(test_objects, LIBS=['cppunit'], CC='g++')
    target_cmd = "./{0}/{0}.test".format(target)
    test_alias = env.Alias(target, [program], program[0].path)
    env.AlwaysBuild(test_alias)

    #cpppath = ["#../LinkItONE.Crest"]
    #cppflags = ['-Wall', '-Wextra', '-g']

    #objects = [
    #    Object(target+"/"+target+".test.cpp", CPPFLAGS=cppflags, CPPPATH=cpppath),
    #    Object("../LinkItONE.Crest/" + target + ".cpp", CPPFLAGS=cppflags, CPPPATH=cpppath)
    #]

    #program = env.Program(target=target+".test", source=objects, LIBS=['cppunit'], CC='g++')

    #test_alias = env.Alias(target+".test", [program], program[0].path)

    #env.AlwaysBuild(test_alias)
